language: ruby

rvm:
  - 2.3.3

addons:
  postgresql: "9.4"

before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"
  - "echo '--colour' > ~/.rspec"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - bundle exec rake db:create db:migrate RAILS_ENV=test
